# Generated by Django 3.2.5 on 2022-02-24 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebNotice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('writer', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('regdate', models.DateTimeField(auto_now=True)),
                ('viewcnt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WebNoticeComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('txt', models.CharField(max_length=500)),
                ('writer', models.CharField(max_length=100)),
                ('notice_id', models.ForeignKey(db_column='notice_id', on_delete=django.db.models.deletion.CASCADE, to='noticeApp.webnotice')),
            ],
        ),
    ]
