# Generated by Django 3.2.5 on 2022-03-02 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=100)),
                ('vol', models.IntegerField(default=100)),
                ('regdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gubun', models.CharField(default='B', max_length=1)),
                ('price', models.IntegerField(default=0)),
                ('quan', models.IntegerField(default=0)),
                ('tquan', models.IntegerField(default=0)),
                ('buyer', models.CharField(max_length=50, null=True)),
                ('seller', models.CharField(max_length=50, null=True)),
                ('tradeyn', models.CharField(default='N', max_length=1)),
                ('time1', models.DateTimeField(auto_now=True)),
                ('time2', models.DateTimeField(null=True)),
                ('code', models.ForeignKey(db_column='code', on_delete=django.db.models.deletion.CASCADE, to='tradeApp.comp')),
            ],
        ),
        migrations.CreateModel(
            name='Ballance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('quan', models.IntegerField(default=0)),
                ('tquan', models.IntegerField(default=0)),
                ('t_price', models.IntegerField(default=0)),
                ('ttime', models.DateTimeField(null=True)),
                ('code', models.ForeignKey(db_column='code', on_delete=django.db.models.deletion.CASCADE, to='tradeApp.order')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ballance',
            constraint=models.UniqueConstraint(fields=('user_id', 'code'), name='unique ballance'),
        ),
    ]
