# Generated by Django 3.2.5 on 2022-03-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballance',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.IntegerField(),
        ),
    ]
