# Generated by Django 3.2.5 on 2022-03-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0002_auto_20220302_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comp',
        ),
        migrations.AddField(
            model_name='ballance',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
