# Generated by Django 3.2.5 on 2022-03-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0002_auto_20220302_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballance',
            name='tquan',
        ),
        migrations.RemoveField(
            model_name='ballance',
            name='ttime',
        ),
        migrations.AddField(
            model_name='ballance',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comp',
            name='d_1price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='tquan',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
