# Generated by Django 3.2.5 on 2022-03-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0003_auto_20220302_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=100)),
                ('vol', models.IntegerField(default=100)),
                ('d_1price', models.IntegerField(default=0)),
                ('regdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ballance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
