# Generated by Django 3.2.5 on 2022-03-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0004_auto_20220302_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tquan',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
