# Generated by Django 3.2.5 on 2022-03-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0006_auto_20220304_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballance',
            name='t_quan',
            field=models.IntegerField(default=0),
        ),
    ]
