# Generated by Django 3.2.5 on 2022-03-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0007_ballance_t_quan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballance',
            name='t_quan',
        ),
    ]
