# Generated by Django 3.2.5 on 2022-03-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0009_d_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_price',
            name='regdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
