# Generated by Django 3.2.5 on 2022-03-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0010_d_price_regdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='u_date',
            field=models.DateTimeField(null=True),
        ),
    ]
