# Generated by Django 3.2.5 on 2022-03-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0012_d_trade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d_trade',
            name='id',
        ),
        migrations.AlterField(
            model_name='d_trade',
            name='day',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
